entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

log:
  level: DEBUG

# Enable API and dashboard
api:
  dashboard: true

providers:
  docker:
    network: "traefik_public"
    exposedByDefault: false
    endpoint: "tcp://socket-proxy:2375"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "contact@jizt.it"
      storage: "acme.json"
      httpChallenge:
        entryPoint: web
